@baseUrl = http://localhost:8080/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiZXhwIjoiMjAyNS0xMi0yNFQyMDoxOTowMi45Njk0MzkyLTAzOjAwIiwiaWF0IjoiMjAyNC0xMi0xNFQyMDoxOTowMi45Njk0MzkyLTAzOjAwIn0.sAzDWurR7xsqHBJGYh9OezOPyS6wiuQq4AnGCuSgxO8

### Upload Image
POST {{baseUrl}}/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="channelName"

testchannel
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpg

< ./test-files/test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW-- 